export const mockModules = {
  study_modules: [
    {
      id: "sm1",
      courses: [
        {
          id: "c1",
          slug: "fullstack",
          photo: "./photos/kitten.jpg",
          course_translations: [
            {
              id: "ct1",
              language: "en",
              name: "Full stack open 2019",
              description: "Deep dive into modern web development.",
              link: "https://fullstackopen.com/en/",
              course: "c1",
            },
            {
              id: "ct2",
              language: "fi",
              name: "Full stack open 2019",
              description: "Syväsukellus moderniin websovelluskehitykseen.",
              link: "https://fullstackopen.com/",
              course: "c1",
            },
          ],
          promote: false,
          status: "ACTIVE",
          start_point: true,
        },
        {
          id: "c2",
          slug: "fullstack-project",
          photo: "./photos/kitten.jpg",
          course_translations: [
            {
              id: "ct3",
              language: "en",
              name: "Full stack project",
              description: "Do modern webmagics.",
              link: "https://fullstackopen.com/en/",
              course: "c2",
            },
            {
              id: "ct4",
              language: "fi",
              name: "Full stack harjoitustyö",
              description: "Rakenna oma websovellus noin 170 tunnissa.",
              link: "https://fullstackopen.com/",
              course: "c2",
            },
          ],
          promote: false,
          status: "ACTIVE",
          start_point: false,
        },
        {
          id: "c3",
          slug: "docker",
          photo: "./photos/whale.jpg",
          course_translations: [
            {
              id: "ct5",
              language: "en",
              name: "DevOps with Docker",
              description: "Become a master of containers.",
              link: "https://docker-hy.github.io/",
              course: "c3",
            },
            {
              id: "ct6",
              language: "fi",
              name: "DevOps with Docker",
              description: "Opi mikropalveluitsemaan Dockerilla.",
              link: "https://docker-hy.github.io/",
              course: "c3",
            },
          ],
          promote: false,
          status: "ACTIVE",
          start_point: true,
        },
      ],
      study_module_translations: [
        {
          id: "smt1",
          language: "en",
          name: "Web development",
          description: "Become a super professionsl web developer and unicorn",
          study_module: "sm1",
        },
        {
          id: "smt2",
          language: "fi",
          name: "Verkko-ohjelmointi",
          description: "Opi ohjelmoimaan verkkosovelluksia ja ole yksisarvinen",
          study_module: "sm1",
        },
      ],
    },
    {
      id: "sm2",
      courses: [
        {
          id: "c4",
          slug: "mooc1",
          photo: "./photos/kitten.jpg",
          course_translations: [
            {
              id: "ct7",
              language: "en",
              name: "Programming with Java I",
              description: "Learn the basics of computer programming.",
              link: "http://moocfi.github.io/courses/2013/programming-part-1/",
              course: "c4",
            },
            {
              id: "ct8",
              language: "fi",
              name: "Ohjelmoinnin MOOC I 2019",
              description:
                "Ohjelmointia Javalla perusteista lähtien. Ei vaadi esitietoja.",
              link: "https://ohjelmointi-19.mooc.fi/",
              course: "c4",
            },
          ],
          promote: true,
          status: "ACTIVE",
          start_point: true,
        },
        {
          id: "c5",
          slug: "mooc2",
          photo: "./photos/kitten.jpg",
          course_translations: [
            {
              id: "ct9",
              language: "en",
              name: "Programming with Java II",
              description: "Direct continuation of part I",
              link: "http://moocfi.github.io/courses/2013/programming-part-2/",
              course: "c5",
            },
            {
              id: "ct10",
              language: "fi",
              name: "Ohjelmoinnin MOOC II 2019",
              description: "Ohjelmoinnin jatkokurssi.",
              link: "https://ohjelmointi-19.mooc.fi/",
              course: "c5",
            },
          ],
          promote: false,
          status: "ACTIVE",
          start_point: false,
        },
        {
          id: "c6",
          slug: "tira",
          photo: "./photos/kitten.jpg",
          course_translations: [
            {
              id: "ct11",
              language: "en",
              name: "Data structures and algorithms",
              description: "Become an algorithmic wizard.",
              link: "https://google.com",
              course: "c6",
            },
            {
              id: "ct12",
              language: "fi",
              name: "Tietorakenteet ja algoritmit",
              description: "Ratkaise kinkkisiä ongelmia salamannopeasti.",
              link: "https://google.com",
              course: "c6",
            },
          ],
          promote: false,
          status: "UPCOMING",
          start_point: false,
        },
      ],
      study_module_translations: [
        {
          id: "smt3",
          language: "en",
          name: "Programming skills",
          description: "Learn programming.",
          study_module: "sm2",
        },
        {
          id: "smt4",
          language: "fi",
          name: "Ohjelmointitaidot",
          description: "Opi ohjelmoimaan.",
          study_module: "sm2",
        },
      ],
    },
  ],
}
