FROM node:11-alpine

RUN apk --no-cache update \
&& apk --no-cache add g++ make bash zlib-dev libpng-dev postgresql-client redis python2 \
&&  rm -fr /var/cache/apk/*

COPY --chown=node . /app

USER node

WORKDIR /app/backend

RUN npm ci

ENV NODE_ENV=production

RUN npm run build

EXPOSE 4000

CMD [ "node", "/app/backend/dist/backend/index.js" ]
