version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        schema: public
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    command: postgres -c log_statement='all'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:5.0.5
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
    - "7001:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data
networks:
  redis-net:
volumes:
  postgres:
  redis-data:
