version: '3'
services:
  postgres:
    image: postgres:15.3
    restart: always
    command: postgres -c log_statement='all'
    ports:
    - "5678:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0.11
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
    - "7001:6379"
    networks:
      - redis-net
    volumes:
      - redis-data:/data
networks:
  redis-net:
volumes:
  postgres:
  redis-data:
