version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        schema: public
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true
  postgres:
    image: postgres:10.3
    restart: always
    command: postgres -c log_statement='all'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
