apiVersion: batch/v1
kind: CronJob
metadata:
  name: course-stats-emailer
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  # every monday at 7:16am
  schedule: "16 7 * * 1"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: course-stats-emailer
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "npm run course-stats-emailer"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-password
