apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-ai-completions
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  schedule: "5/10 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: fetch-ai-completions
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "npm run fetch-ai-completions"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password
