apiVersion: batch/v1
kind: CronJob
metadata:
  name: fetch-user-field-values
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  schedule: "30 2 * * *"
  startingDeadlineSeconds: 900
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: fetch-user-field-values
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "pnpm fetch-user-field-values"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-password
                - name: CONFIG_NAME
                  value: "userFieldValues"

