apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-frontend
  labels:
    app: {{ include "helm.fullname" . }}-frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: frontend-http
  selector:
    app: {{ include "helm.fullname" . }}-frontend
