apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-organizations
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  schedule: "15 0 * * *"
  startingDeadlineSeconds: 900
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: import-organizations
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "pnpm import-organizations"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-password
