{{- range $cron := .Values.cronjob.masaryk.crons }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: masaryk-stats-emailer-{{$cron.id}}
  labels:
    {{- include "helm.labels" $ | nindent 4 }}
spec:
  schedule: "0 10 {{$cron.day}} {{$cron.month}} *"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" $ | nindent 8 }}
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: masaryk-stats-emailer
              image: "{{ $.Values.image.repository }}/moocfi-backend:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              command: ["sh", "-c", "npm run masaryk-stats-emailer"]
              envFrom:
                - secretRef:
                    name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-password
                - name: REDIS_SENTINELS
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-sentinels
                - name: REDIS_SENTINEL_MASTER_NAME
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-sentinel-master-name
{{- end }}
