apiVersion: batch/v1
kind: CronJob
metadata:
  name: prague-stats-emailer
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  # Run at 10:00 AM on 30th of November
  schedule: "0 10 24 1 *"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: prague-stats-emailer
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "npm run prague-stats-emailer"]
              envFrom:
                - secretRef:
                    name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: new-redis
                      key: redis-password
