apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: resync-user-app-datum
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  schedule: "0 3 1 * *"
  # at 3:00 am, 1st day of every month
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  jobTemplate:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      activeDeadlineSeconds: 7200
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: resync-user-app-datum
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "npm run fetch-user-app-datum"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password
                - name: CONFIG_NAME
                  value: "resyncUserAppDatum"
