apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: send-ai-statistics
spec:
  schedule: "1 7 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1000
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: send-ai-statistics
              image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command: ["sh", "-c", "npm run send-ai-statistics"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password
