apiVersion: v1
kind: Service
metadata:
  name: ws
  labels:
    app: {{ include "helm.fullname" . }}-backend
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 9000
    name: "ws"
    targetPort: ws
  selector:
    app: {{ include "helm.fullname" . }}-backend
    {{- include "helm.selectorLabels" . | nindent 4 }}
