apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-user-points
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: kafka-consumer-user-points
      {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.kafkaConsumer.userPoints.replicaCount }}
  template:
    metadata:
      labels:
        app: kafka-consumer-user-points
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: kafka-consumer-user-points
          image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["sh", "-c", "npm run kafka-consumer-user-points"]
          imagePullPolicy: Always
          ports:
            - name: backend-http
              containerPort: 4000
          resources:
            limits:
              memory: 1000Mi
              cpu: 200m
            requests:
              memory: 500Mi
              cpu: 50m
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          volumeMounts:
            - name: google-cloud-storage-serviceaccount
              mountPath: "/etc/gcs"
              readOnly: true
      volumes:
        - name: google-cloud-storage-serviceaccount
          secret:
            secretName: google-cloud-storage-serviceaccount
            items:
              - key: account.json
                path: account.json
