apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-exercises
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: kafka-consumer-exercises
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer-exercises
    spec:
      containers:
        - name: kafka-consumer-exercises
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["sh", "-c", "npm run kafka-consumer-exercises"]
          imagePullPolicy: Always
          ports:
            - name: backend-http
              containerPort: 4000
          resources:
            limits:
              memory: 500Mi
            requests:
              memory: 256Mi
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          volumeMounts:
            - name: google-cloud-storage-serviceaccount
              mountPath: "/etc/gcs"
              readOnly: true
      volumes:
        - name: google-cloud-storage-serviceaccount
          secret:
            secretName: google-cloud-storage-serviceaccount
            items:
              - key: account.json
                path: account.json
      initContainers:
        - name: moocfi-backend-run-migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["sh", "-c", "npx prisma deploy"]
          envFrom:
          - secretRef:
              name: backend-secret
