apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge
  labels:
    app: kafka-bridge
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: kafka-bridge
  selector:
    app: kafka-bridge
    {{- include "helm.selectorLabels" . | nindent 4 }}
