version: '3'
services:
  auth-backend:
    build: .
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
