version: 2.1
orbs:
  helm: circleci/helm@1.0.0
jobs:
  code_style:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: "npm ci"
      - run:
          name: "Check code style"
          command: "bin/check-code-style.sh"
      - run:
          name: "ESLint"
          command: "bin/eslint.sh"
      - helm/install-helm-client:
          version: v3.2.4
      - run:
          name: "Helm"
          command: "bin/helm.sh"

  build_frontend:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build frontend image"
          command: "bin/build-docker-frontend.sh"
      - run:
          name: "Push image if on master"
          command: "bin/push-docker-frontend-image.sh"

  build_backend:
    docker:
      - image: eu.gcr.io/moocfi-public/cloud-sdk-node:latest
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: testing
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build backend image"
          command: "bin/build-docker-backend.sh"
      - run:
          name: Build
          environment:
            NEW_RELIC_NO_CONFIG_FILE: "true"
            NEW_RELIC_LICENSE_KEY: ""
          command : |
            cd backend
            cp .env.example .env
            npm i
            npm run generate:nexus
            npm run build
            npm run create-test-db
      - run:
          name: "Run tests"
          command: |
            cd backend
            npm run test
            cd ..       
      - run:
          name: "Push image if on master"
          command: "bin/push-docker-backend-image.sh"

  deploy_to_production:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker      
      - helm/install-helm-client:
          version: v3.2.4
      - run:
          name: install envsubst
          command: apt-get install -qq -y gettext
      - run:
          name: "Deploy"
          command: "bin/ci-update-deployments.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_frontend
      - build_backend
      - code_style
      - deploy_to_production:
          requires:
            - build_frontend
            - build_backend
            - code_style
          filters:
            branches:
              only:
                - master
