apiVersion: v1
kind: Service
metadata:
  name: moocfi-shibbo-connect
  labels:
    app: moocfi-shibbo-connect
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: moocfi-shibbo-connect
  selector:
    app: moocfi-shibbo-connect
    {{- include "helm.selectorLabels" . | nindent 4 }}
