apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-shibbo-connect
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: moocfi-shibbo-connect
      {{- include "helm.selectorLabels" . | nindent 6 }}
  replicas: {{ .Values.kafkaBridge.replicaCount }}
  template:
    metadata:
      labels:
        app: moocfi-shibbo-connect
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: moocfi-shibbo-connect
          image: "{{ .Values.image.repository }}/moocfi-backend:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["sh", "-c", "npm run shibbo"]
          imagePullPolicy: Always
          # livenessProbe:
          #   httpGet:
          #     path: /connect/healthz
          #     port: 6202
          #   initialDelaySeconds: 60
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /connect/healthz
          #     port: 6202
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          ports:
            - name: moocfi-shibbo-connect
              containerPort: 6202
          resources:
            limits:
              memory: 1000Mi
              cpu: 50m
            requests:
              memory: 256Mi
              cpu: 10m
          envFrom:
          - secretRef:
              name: backend-secret
          - secretRef:
              name: shibboleth-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
