// generated Thu May 28 2020 13:48:54 GMT+0300 (Eastern European Summer Time)

export { default as addEmailTemplateQueries } from "./EmailTemplate"
export { default as addExerciseQueries } from "./Exercise"
export { default as addExerciseCompletionQueries } from "./ExerciseCompletion"
export { default as addOpenUniversityRegistrationLinkQueries } from "./OpenUniversityRegistrationLink"
export { default as addCompletionQueries } from "./completion"
export { default as addCourseQueries } from "./course"
export { default as addCourseAliasQueries } from "./courseAlias"
export { default as addCourseOrganizationQueries } from "./courseOrganization"
export { default as addCourseTranslationQueries } from "./courseTranslation"
export { default as addCourseVariantQueries } from "./courseVariant"
export { default as addOrganizationQueries } from "./organization"
export { default as addRegisteredCompletionQueries } from "./registeredCompletion"
export { default as addServiceQueries } from "./service"
export { default as addStudyModuleQueries } from "./studyModule"
export { default as addStudyModuleTranslationQueries } from "./studyModuleTranslation"
export { default as addUserQueries } from "./user"
export { default as addUserCourseProgressQueries } from "./userCourseProgress"
export { default as addUserCourseServiceProgressQueries } from "./userCourseServiceProgress"
export { default as addUserCourseSettingsQueries } from "./userCourseSettings"
export { default as addUserOrganizationQueries } from "./userOrganization"
