apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-user-points
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: kafka-consumer-user-points
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer-user-points
    spec:
      containers:
        - name: kafka-consumer-user-points
          image: ${BACKEND_IMAGE}
          command: ["sh", "-c", "npm run kafka-consumer-user-points"]
          imagePullPolicy: Always
          ports:
            - name: backend-http
              containerPort: 4000
          resources:
            limits:
              memory: 10000Mi
            requests:
              memory: 1000Mi
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          volumeMounts:
            - name: google-cloud-storage-serviceaccount
              mountPath: "/etc/gcs"
              readOnly: true
      volumes:
        - name: google-cloud-storage-serviceaccount
          secret:
            secretName: google-cloud-storage-serviceaccount
            items:
              - key: account.json
                path: account.json
      initContainers:
        - name: moocfi-backend-run-migrations
          image: ${BACKEND_IMAGE}
          command: ["sh", "-c", "npm run prisma-deploy"]
          envFrom:
          - secretRef:
              name: backend-secret
