apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-bridge
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: kafka-bridge
  replicas: 3
  template:
    metadata:
      labels:
        app: kafka-bridge
    spec:
      containers:
        - name: kafka-bridge
          image: ${BACKEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - name: kafka-bridge
              containerPort: 4000
          resources:
            limits:
              memory: 1000Mi
            requests:
              memory: 256Mi
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
