apiVersion: v1
kind: Service
metadata:
  name: kafka-bridge
  namespace: moocfi
  labels:
    app: kafka-bridge
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: kafka-bridge
  selector:
    app: kafka-bridge
