apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: user-course-progress
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 107374182
