# Puppeteer/Headless Chrome needs this
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kafka-consumer-restarter
spec:
  concurrencyPolicy: Forbid
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: kafka-consumer-restarter
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - 'kubectl'
                - 'rollout'
                - 'restart'
                - '"deployment/kafka-consumer-exercises" "deployment/kafka-consumer-user-course-progress-batch" "deployment/kafka-consumer-user-course-progress-realtime" "deployment/kafka-consumer-user-points-batch" "deployment/kafka-consumer-user-points-realtime"'
