# Puppeteer/Headless Chrome needs this
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kafka-consumer-restarter
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  schedule: "2 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: kafka-consumer-restarter
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - /bin/sh
                - -c
                - |
                  kubectl rollout restart deployment/kafka-consumer-exercises
                  kubectl rollout restart deployment/kafka-consumer-user-course-progress-batch
                  kubectl rollout restart deployment/kafka-consumer-user-course-progress-realtime
                  kubectl rollout restart deployment/kafka-consumer-user-points-batch
                  kubectl rollout restart deployment/kafka-consumer-user-points-realtime
