apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-backend
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: moocfi-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: moocfi-backend
    spec:
      containers:
        - name: moocfi-backend
          image: ${BACKEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - name: backend-http
              containerPort: 4000
          resources:
            limits:
              memory: 1500Mi
            requests:
              memory: 256Mi
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          volumeMounts:
            - name: google-cloud-storage-serviceaccount
              mountPath: "/etc/gcs"
              readOnly: true
      volumes:
        - name: google-cloud-storage-serviceaccount
          secret:
            secretName: google-cloud-storage-serviceaccount
            items:
              - key: account.json
                path: account.json
      initContainers:
        - name: moocfi-backend-run-migrations
          image: ${BACKEND_IMAGE}
          command: ["sh", "-c", "npm run prisma-deploy"]
          envFrom:
          - secretRef:
              name: backend-secret
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
