apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: fetch-avoin-links
  namespace: moocfi
spec:
  schedule: "15 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 1800
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: fetch-ai-completions
              image: ${BACKEND_IMAGE}
              command: ["sh", "-c", "npm run fetch-avoin-links"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password