apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-frontend
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: moocfi-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: moocfi-frontend
    spec:
      containers:
        - name: moocfi-frontend
          image: gcr.io/moocfi/moocfi-frontend:build-1559554411-184e9d3ab85f6cfcedabfbaf4ebaeb3d3f826ad7
          imagePullPolicy: Always
          ports:
            - name: frontend-http
              containerPort: 3021
