apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-frontend
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: moocfi-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: moocfi-frontend
    spec:
      containers:
        - name: moocfi-frontend
          image: gcr.io/moocfi/moocfi-frontend:build-1559904282-f008139aa37b55e527e9d554f005ef0c9d8f3a39
          imagePullPolicy: Always
          ports:
            - name: frontend-http
              containerPort: 3021
