apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-frontend
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: moocfi-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: moocfi-frontend
    spec:
      containers:
        - name: moocfi-frontend
          image: gcr.io/moocfi/moocfi-frontend:build-1560942458-8c8d07a30d31941f43aad21cef32f85ce1106f80
          imagePullPolicy: Always
          ports:
            - name: frontend-http
              containerPort: 3021
