apiVersion: apps/v1
kind: Deployment
metadata:
  name: moocfi-frontend
  namespace: moocfi
spec:
  selector:
    matchLabels:
      app: moocfi-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: moocfi-frontend
    spec:
      containers:
        - name: moocfi-frontend
          image: gcr.io/moocfi/moocfi-frontend:build-1561036031-34764690c6093d2953f7838828c1e38d2146f15c
          imagePullPolicy: Always
          ports:
            - name: frontend-http
              containerPort: 3021
