apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prisma
  name: prisma
  namespace: moocfi
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: prisma
    spec:
      containers:
        - name: prisma
          image: prismagraphql/prisma:1.33
          envFrom:
            - secretRef:
                name: backend-secret
          env:
            - name: PRISMA_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: prisma-configmap
                  key: PRISMA_CONFIG
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          ports:
            - containerPort: 4466
          resources: {}
      restartPolicy: Always
status: {}
