apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: remove-duplicate-completions
  namespace: moocfi
spec:
  schedule: "4/30 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: remove-duplicate-completions
              image: ${BACKEND_IMAGE}
              command: ["sh", "-c", "npm run remove-duplicate-completions"]
              envFrom:
              - secretRef:
                  name: backend-secret
              env:
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: redis
                      key: redis-password
