# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

backend:
  replicaCount: 2
  connectionLimit: 5

frontend:
  replicaCount: 2

kafkaBridge:
  replicaCount: 2
  connectionLimit: 1

kafkaConsumer:
  connectionLimit: 1
  topic:
    exercises:
      replicaCount: 1
    userCourseProgress:
      replicaCount: 1
    userCourseProgressRealtime:
      replicaCount: 1
    userPoints:
      replicaCount: 1
    userPointsRealtime:
      replicaCount: 1
    userCoursePoints:
      replicaCount: 3
    userCoursePointsRealtime:
      replicaCount: 1

shibboTest:
  replicaCount: 0

email:
  # controls whether the background email service should be running
  enabled: true

expireUserOrganizationJoinConfirmations:
  # controls whether the background service to expire user organization join confirmations should be running
  enabled: false

image:
  repository: eu.gcr.io/moocfi
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: www.mooc.fi
  tls:
    - secretName: moocfi-tls
      hosts:
        - points.mooc.fi
        - mooc.fi
        - www.mooc.fi

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

cronjob:
  prague: # @vse.cz report, see backend/bin/pragueStatsEmailer.ts
    crons:
      - id: "0"
        day: 28
        month: 1
      - id: "1"
        day: 2
        month: 6
      - id: "2"
        day: 22
        month: 8
      - id: "3"
        day: 15
        month: 12
  purkyne: # @ujep.cz report, see backend/bin/purkyneStatsEmailer.ts
    crons:
      - id: "0"
        day: 30
        month: 6
      - id: "1"
        day: 31
        month: 8
      - id: "2"
        day: 20
        month: 12
  masaryk: # @muni.cz report, see backend/bin/masarykStatsEmailer.ts
    crons:
      - id: "0"
        day: 15
        month: 1
      - id: "1"
        day: 13
        month: 6
